_target_: rgbd_dataset.datasets.Isaacsim.Isaacsim
dataset_name: "isaacsim"
base_path: ???
scene: 
- chair1
- chair2
width: 960
height: 540
resized_width: -1
resized_height: -1
sequence_start: 0
sequence_end: -1
sequence_stride: 1
relative_pose: False
depth_scale: 1000.0
point_cloud: true
depth_trunc: 12.0
