_target_: rgbd_dataset.datasets.Scannetpp.Scannetpp
base_path: ???
scene: 4318f8bb3c
width: 1920
height: 1440
fx: 1433.0947
fy: 1433.0947
cx: 955.62964
cy: 723.15564
resized_width: -1
resized_height: -1
sequence_start: 0
sequence_end: -1
sequence_stride: 50
relative_pose: False
depth_scale: 1000.0
point_cloud: true
depth_trunc: 8.0
